default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DATABASE_POOL_SIZE') { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { '5432' } %>
  user: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  database: <%= ENV.fetch('DATABASE') { 'dog_walking_api_development' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'postgres' } %>

development:
  <<: *default

test:
  <<: *default
  database: dog_walking_api_test

production:
  <<: *default
  database: dog_walking_api_production

